### ISSUE TITLE
Unsure about escape sequences in Character Constants

### ISSUE THREAD

**Issue by alaksana96** [LangProc/langproc-2016-cw#10]
I am using: http://port70.net/~nsz/c/c89/c89-draft.txt as a specification.

In section 3.1.3.4 Character Constants:
```
          character-constant:
                  ' c-char-sequence' 
                  L' c-char-sequence' 

          c-char-sequence:
                  c-char
                  c-char-sequence c-char

          c-char:
                  any member of the source character set except
                   the single-quote ', backslash \, or new-line character
                   escape-sequence

          escape-sequence:
                  simple-escape-sequence
                  octal-escape-sequence
                  hexadecimal-escape-sequence

          simple-escape-sequence: one of
                  \'  \"  \?  \\
                  \a  \b  \f  \n  \r  \t  \v

          octal-escape-sequence:
                  \  octal-digit
                  \  octal-digit octal-digit
                  \  octal-digit octal-digit octal-digit

          hexadecimal-escape-sequence:
                  \x  hexadecimal-digit
                  hexadecimal-escape-sequence hexadecimal-digit

```
Are escape sequences detected like:
`\a`
Or like:
`'\a'`

Also, under _c-char_:

> any member of the source character set except the single-quote ', backslash \, or new-line character escape-sequence

Does this include all escape sequences except \ and new line?

**Comment by tnugent97** [comment]
I think escaped sequences are detected like '\a', but I am also confused about the second point.
Like you said, the ANSI spec says a c-char is anything _except_ **' \ and \n**, but then \n is included as part of the escaped sequences.

So is \n included or not?

**Comment by m8pple** [comment]
These very detailed readings of the spec are good for understanding
how specs work (and the level of detail), but you might end up over-analysing
a bit. In particular, these specs are used both to tokenise legal C programs,
but _also_ to reject illegal C programs. However, your job is somewhat easier,
as you only have to tokenise legal programs.

A character literal is a form of [delimited string](https://en.wikipedia.org/wiki/Delimiter),
so the things we really care about are that it starts with one delimiter, and ends with
the other. The only particularly difficult case is if the ending delimiter needs to be
expressed within the characters being delimited, so in this case, what happens if
a `'` appears within a string literal? I'd break the problem down into three things:

   1. The start delimiter has to appear
   2. Multiple characters appear which are either:
      a. Not the delimiter
      b. The escaped delimited
   3. The end delimited has to appear

Also, bear in mind that you can always see what an existing C compiler does, both
in terms of seeing whether code fragments compile, and in seeing what characters
it ends up printing.
