### ISSUE TITLE
well-formed = valid?

### ISSUE THREAD

**Issue by maccth** [LangProc/langproc-2016-cw#13]
Sorry to be pedantic about things but does the input being 'well-formed' mean that it will never constitute an `Invalid` token class?

I ask because I thought well-formed meant that it meets *the* specification (scary), and `Invalid` is indeed part of the specification.

Thanks in advance!

'I like the cold weather. It means you get work done' - Noam Chomsky

**Comment by m8pple** [comment]
Yes - well-formed as defined by the input language, so you never technically
need to worry about an invalid token.

The main purpose of Invalid is so that people have some meaningful fall-back
for what to do if none of their lexer patterns match. You could just let it
fall through and produce invalid json, but it is neater to have some kind of
well-defined action - I find it nags at me knowing that the lexer doesn't
have something to do for everything.

We'll briefly see Chomsky again tomorrow. Sadly not for long; most of
his interesting work is beyond the linguistics arena.
