### ISSUE TITLE
Array of JSON Dictionaries Output Format

### ISSUE THREAD

**Issue by drovick** [LangProc/langproc-2016-cw#14]
This may be a stupid issue considering that far more competent people seem not have needed to post it, but I am confused about the following:

(a) will the array of JSON dictionaries need to a global variable for the lexer submission and/or for latter parts of the coursework?

(b) how do you (DT) intend to test the lexer submission, and will that information be relevant to how we build our submission, ie is there a requirement/preference that the array of dictionaries be printed to stdout?

**Comment by m8pple** [comment]
It's quite a reasonable question, as I'm deliberately playing with the
concept of data-structures as:
- memory: regions of RAM, linked together by pointers
- storage: characters on disk, representing structured data
- streams: characters in flight, allowing data to move between programs and places

This (rather intentionally) relates to some of the other things you are
looking at this term:

- distributed systems: When implementing RPC we need to take an in-memory
  data-structure, marshal it into a stream, then un-marshal it back into an in-memory
  data-structure. JSON is one way that you can actually implement this

- databases: Databases require you to be able to query and work with sets of
  tuples. You may not think of it this way, but what I've defined for the tokens is
  actually a database table. Each token has a set of columns; each token is a row;
  so the tokens within the JSON array represent the table data.

The JSON output is pure text, so there is no notion of global variables, nor does it
explicitly link to other parts of the coursework. When we talk about a JSON array,
it means a sequence of JSON values that is surrounded by '[' ']', rather than an
array as an in-memory data-structure. So you may _choose_ to use some sort of
global array within your lexer, but that would be an implementation detail.  The
only thing that the API cares about is what comes out over stdout.

So in terms of testing, I will:
- Stream C source code into your lexer
- Capture the JSON that your lexer prints to stdout (e.g. printf or std::cout).
- Parse the JSON into an in-memory data-structure in a completely different program
- Walk the array of tokens in that separate program, checking whether each
  token has the attributes I expect.

I would observe that the information required per token during output is
very regular. So if you set up attributes/globals correctly, the output code
could be akin to (note, this is definitely pseudo-code):

````
extern int g_streamLine; // Updated in lexer

std::cout<<"[\n";
while(1){
    int type=yylex();
    std::string classStr=typeToClass[type];
    std::string text=yytext;
    std::cout<<"{ Class=\""<<classStr<<"\", Text=\""<<text<<\"" , StreamLine="<<g_streamLine<<"},\n";
}
std::cout<<"{}\n"; // Empty token to make life easier
std::cout<<"]\n";
````
