### ISSUE TITLE
Rewrite the lexer?

### ISSUE THREAD

**Issue by Carotti** [LangProc/langproc-2016-cw#16]
Because of the way which we wrote the lexer, everything is given to bison as a token of type either `KEYWORD`, `OPERATOR`, `CONSTANT`, `STRING_LITERAL` or `INVALID`.

This means that we can't distinguish say a type specifier from other keywords within bison. So if we were writing a (simplified) rule for a declaration, you would expect something like:

```bison
DECLARATION : TYPE_SPECIFIER IDENTIFIER ';' { ... }

TYPE_SPECIFIER : "int" { ... }
			   | "float" { ... }
               | "char" { ... }
```

However, we don't have access to a token `TYPE_SPECIFIER`, nor can we match it literally. If I'm missing something about how to match literals in bison, and we can still match these despite everything being tokenised, I'd love to know how to do that.

Since I can't figure out a way for us to match literals in the way that I outlined above, I see two other ways of dealing with this.

#### Option 1: Rewrite the lexer to include all terminals as required by bison

So we would do something in bison like
```
$token TYPE_SPECIFIER
```

and in flex

```
int|float|char { ... ; return TYPE_SPECIFIER }
;			   { ... ; return T_SEMICOLON }
```

This isn't ideal, because it means rewriting the lexer (and therefore breaking `bin/c_lexer`). However, I feel like this is the "intended" way of doing things with bison/flex.

#### Option 2: Define a much more generalised grammar and then check for syntax errors in the code

With this option, the lexer stays the same but in bison you would write something like
```bison
DECLARATION : KEYWORD IDENTIFIER OPERATOR {
	if (*$1 != "int" && *$1 != "float" && *$1 != "char") {
    	std::cout << "Unexpected keyword: " << *$1 << std::endl;
        exit(EXIT_FAILURE);
    }
    if (*$3 != ";") {
    	std::cout << "Unexpected operator: " << *$3 << std::endl;
        exit(EXIT_FAILURE);
    }
}
```

I'd really rather not do this, because it's going to end up with code splashed all around bison to do something which could be avoided with a more specific grammar.

However, I also think this has the advantage of giving much more specific errors.

Unfortunately i'm fairly sure this approach will lead to rule-conflicts as well ie `KEYWORD` `IDENTIFIER` `OPERATOR` could be a declaration but it could also be an expression or statement.

----

So I guess basically I am asking which approach is best, or if there are any other options, before I pick my lexer apart.

**Comment by m8pple** [comment]
Ah, I think this is a clash between my goals of getting something simple and
low-effort enough that can be assessed as a milestone, while also trying to
make it useful as a building block for the compiler.

The classes that I got you to print out in JSON are not intended to be the
token types returned from your lexer. As you point out, they are not sufficient
for grammatical purposes, as you need to talk about a specific keyword,
rather than the general class of keyword. The main reason for requiring
the class field is to try to make sure people are able to do something with
token values, rather than just write the regexes.

Last year I also asked for a unique per-token value in the lexer milestone
(in addition to the class), but it caused a lot of confusion, so I took it out.
But ultimately you still need a unique per-token value to return from
yylex.

So you definitely don't want option 2 - as you point out, it becomes horrible
to maintain, and you'll end up re-implementing parser features in actions.

Option 1 is the right direction, but you probably want to go further. So
rather than:
````
int|float|char { ... ; return TYPE_SPECIFIER }
;			   { ... ; return T_SEMICOLON }
````
you'd want:
````
int    { return T_INT; }
float { return T_FLOAT; }
char { return T_CHAR; }
;       {return T_SEMICOLON; }
````

Thanks for pointing this out; it didn't occur to me that it might appear that I
was suggesting doing the grammar in terms of the token class, but I see how
it might look.

Oh, and BTW: great bug report. Thanks for putting the time in to outline the issue
and the alternatives.

-----

BTW, there is a way of having literals in bison, as long as you establish a
mapping. If you had (invented grammar):
````
%token T_INT
%%
VAR : T_INT T_ID
````
then you can tell bison what literal the token is, and use the string:
````
%token T_INT "int"
%%
VAR : "int" T_ID
````
See the later part of the bison `%token` decl section:
https://www.gnu.org/software/bison/manual/html_node/Token-Decl.html

I often use this when writing grammars, but beware: it is up to you to make
sure that the literal you bind to the token in bison is the _same_ literal you
match against in flex. Some people consider it bad practice because of the
leakage and potential for drift between the two sides, and think the parser
should know _nothing_ about the characters that the token represents.

**Comment by Carotti** [comment]
Thanks for taking the time to respond!

I've sort of already begun making progress in splitting up my lexer into many more individual tokens. Is it alright therefore that what we submit for the parser no longer builds a working `bin/c_lexer`? 

My justification for the way I originally built my lexer is basically that I'm just lazy. It seemed the easiest way to go from inputted C to the defined JSON output was to group tokens by the JSON classes rather than individually. Once it was outputting JSON correctly, "Job Done!". When I built it, I hadn't even looked at bison and how it interacted with flex. Things like knowing that `%token` definitions generate an enum in `xxx.tab.hpp` would have definitely been useful at the time!

I feel like the lexer depends (both intuitively, and in my makefile...) on the parser more than I had first thought!

**Comment by m8pple** [comment]
Yes, at this point you can break your bin/c_lexer if it is convenient. It is quite likely
that while the regexes will stay the same, you may want to change the actions/return types.

The linkage between the lexer and the parser is something that may not be so clear until
one has written the parser. There was an argument for putting the C lexer deliverable
after the parser lab, but I worried about delaying things too far into term. So I'm not
so worried about people heading straight for the thing that results in ./test_lexer.sh
saying it all passes, as at least the regexes should be right, even if the actions are
wrong.

If you're facing rewriting lots of actions, you may want to consider the power of... regexes!

If you have lots of lex rules of the form:
````
int { return KEYWORD; }
float { return KEYWORD; }
while { return KEYWORD; }
````
and you want to turn them into:
````
int { return T_int; }
float { return T_float; }
while { return T_while; }
````
Then something like:
````
s/^([a-z]+)\s+{\s+return KEYWORD;\s+}\s+$\1 { return T_\1; }/g
````
might help you fix lots of them in one go.

BTW, this might look like a joke (given the above regex), but it is actually
not. Once you are fairly comfortable with regexes and pattern substitutions,
then an editor with a regex driven search and replace can be quite effective,
as it takes less time to refine the regex than it does to modify 30 lines of code.

Of course, you are limited to _regular_ replacements; anything more needs
context-free matching, which is where refactoring tools come in.
