### ISSUE TITLE
Behaviour with ill-formed C90

### ISSUE THREAD

**Issue by daveshah1** [LangProc/langproc-2016-cw#18]
Does our parser/compiler have to fail on code that it is not C90 compliant?

For example, can our code accept C99-style mixed declarations/statements and non-constant expressions in initialiser lists because it would actually be more work to trap those cases? 

On a similar note, if given completely invalid code does it have to fail with a sensible error and non-zero return code or would silent failure and broken output be acceptable (although that would obviously not be ideal)?

**Comment by m8pple** [comment]
The contract from my side is that the input will be C90 compliant,
so the handling of both code that is invalid or code that is more
recent is up to you.

As you suggest, it is often more effort to explicitly disallow certain
C99 stuff, so you might as well just let it be handled. Things like
non-constant initialisers and mixed decl/stats often come for free in
a modern-ish language and compiler flow. (As an aside, the difference
in available resources between now and then is quite surprising - for us
it is easy to build a symbol table and use recursive functions, but back
then they would have had to worry about exceeding available core memory.)

For invalid code - yes, I would encourage you to have some kind of
error output and non-zero return code, mainly because it makes
your life easier when debugging. There is a chance that your
basic error handling code will save you when the code is _valid_,
but your compiler happens not to handle it.
