### ISSUE TITLE
What is 'valid C'? (does anyone really know)

### ISSUE THREAD

**Issue by tnugent97** [LangProc/langproc-2016-cw#19]
So upon inspection of the ANSI C spec as you do on a standard Tuesday afternoon, I noticed something that has decreased my confidence on compilers from "_High_" to "_Low_" on the David Thomas Scale. 

Apparently the following is valid C?
```
x++ = ++y = z;
(start from assignment-expression)
```
And also
```
int int int x;
(start from declaration)
```

Why would you allow something in your grammar such as the above, when it has no semantics (i.e. as far as I can tell it doesn't compile). Surely the whole point of the grammar is to _stop_ situations like this occurring? If this kind of thing is allowed, then when in the process do you recognise this as an error (for me it made sense in the parser, but is it even later at code gen?)

This makes me wonder what exactly 'valid C' is? (maybe more of a philosophical question)
What kind of 'valid C' will our compilers be tested against?
Do our compilers need to be able to recognise this 'valid' but meaningless C?

**Comment by m8pple** [comment]
The differences you're seeing are exactly the kinds
of things you'd catch in the post-parse analysis,
as they are the kinds of things that are almost impossible
to catch in a context-free parser.

As to whether it is valid C:

     $ echo "int main(){ int x=0, y=0, z=0; x++ = ++y = z; }" > tmp.c

     dt10@GABBY ~
     $ gcc -pedantic tmp.c
     tmp.c: In function ‘main’:
     tmp.c:1:42: error: lvalue required as left operand of assignment
     int main(){ int x=0, y=0, z=0; x++ = ++y = z; }
                                              ^
So there is a second-level analysis pass which happens after
parsing, where it goes beyond just the parsing derivation,
and looks at the types of the expressions.

Similarly, if we try the multiple ints:

     dt10@GABBY ~
     $ echo "int int int x;" > tmp.c

     dt10@GABBY ~
     $ gcc -pedantic tmp.c
     tmp.c:1:5: error: two or more data types in declaration specifiers
      int int int x;
          ^
     tmp.c:1:9: error: two or more data types in declaration specifiers
      int int int x;
              ^

In both of these cases we could (I think) capture the semantics
in the parser, but it is debatable whether it is worth the effort,
rather than catching it later on.

So consider the complete (infinite) set of valid C programs,
let's call it... C.

A particular grammar G1 could be used to parse C programs,
and will recognise an (infinite) set of C programs. However,
it is not necessarily the case that C = G1 (i.e. the two
sets are equal). It is much more likely that G1 is actually
a superset of valid C programs, so C \subset G1. This is
because most fast parsers will be context-free, and so
over-approximate the set C. However, it should definitely
be the case that C - G1 = \empty, i.e. there should be nothing
recognised by G1 that is _not_ a valid C program.

For the first example we could try to capture the difference
between an read-write expression (LEXPR) and a readable expression (REXPR):

     LEXPR : ID
           | '*' REXPR
           | REXPR '->' ID
           | REXPR
           ;

     REXPR : LEXPR
           | '-' EXPR
           | '~' EXPR
           ;

This gets very complicated very quickly (I'd need to think it
through more carefully), and in many cases you can
do it in a context-free grammar (as the type of a non-terminal
becomes context-sensitive).

However, we might manage to get a new grammar G2, which has the
property that G2 \subset G1. But it is still likely the case
that C \subset G2.

So we end up with the following, which links back to the
difference between syntax and semantics which we saw in
an earlier lecture:

1 - The examples are valid according to _some_ definitions of
     the C grammar.

2 - They could equally be invalid according to a more complicated
     and tighter C grammar.

3 - They are definitely invalid according to the C specification,
     regardless of which grammar is used.

So the question of "what is valid C" comes down to whether
a given input program has valid semantics under the definition
given in the spec. The spec is self is more than just the
grammar, and the grammar they give is just an example. Your
are free to use a different grammar if it does the same
thing.


If we were to handle things at the AST level, we could simply
pass all expressions as the same thing, and do something like
this:

     class Expr
     {
         virtual bool isAssignable() const =0;
     };

     class PointerDeRefExpr
         : public Expr
     {
         virtual bool isAssignable() const
         { return true; }   // *(P) can be assigned
     };

     class PostIncrementExpr
         : public Expr
     {
         virtual bool isAssignable() const
         { return false; }   // (E)++ is not assignable
     };


David Thomas
