### ISSUE TITLE
When printing out StringLiteral text in JSON which format do we use?

### ISSUE THREAD

**Issue by ps-george** [LangProc/langproc-2016-cw#2]
`{ "Class" : "StringLiteral", Text : ""hi"" }`
or
`{ "Class" : "StringLiteral", Text : "hi" }`

Given that for a constant: 
`{ "Class" : "Constant", Text : "1.0" }`
I would assume the first example, but it looks odd.

Edit: The first is not valid JSON, so I assume the second, with all internal quotes escaped.
e.g. `{ "Class" : "StringLiteral", Text : "hi this is a \"stringliteral\"" }`

**Comment by m8pple** [comment]
My immediate reaction was yes (to the edit), it's the second method. The
"payload" of a string literal doesn't actually contain the quotes, so it makes
sense not to include them. Any AST that included the quotes would just
be wasting bytes.

But... re-reading the spec:

> The original text of the token, not including any surrounding white-space.

The token as matched to the text _does_ contain the quotes. So my
reasoning above is incorrect, and it seems genuinely ambiguous.
So I think that then requires me to adapt my testing in order to
match both sides of the spec - I will suggest that outer quotes should
be stripped,  but I will accept string literals with or without surrounding quotes. 

However, internally I think it remains consistent, as if a " or \ appears
within the original text, there is a well defined way of representing
that in JSON so that it can be recovered exactly.

Good catch.
