### ISSUE TITLE
'Include' Tests

### ISSUE THREAD

**Issue by luisi-at** [LangProc/langproc-2016-cw#20]
Can you explain why in the comparison for this test there is a message of `stripping surrounding quotes for token index <index> due to mild ambiguity in the spec`? I'm looking through the logs and my SourceFile string is an exact match aside from these loose quotations, but yet the result of the test is still a fail. Why exactly is this?

**Comment by m8pple** [comment]
Ah, I see the problem. The message about stripping quotes is actually applying to the reference
JSON, as it loads that before it loads the student JSON. So for example, for "include-0" we have
the reference JSON:

````
[
{ "Text":"int", "Class":"Keyword", "StreamLine":8, "SourceFile":"\"test-data/src/var-decl-1.c\"", "SourceLine":1, "SourceCol":1 }, 
{ "Text":"x", "Class":"Identifier", "StreamLine":8, "SourceFile":"\"test-data/src/var-decl-1.c\"", "SourceLine":1, "SourceCol":5 }, 
{ "Text":";", "Class":"Operator", "StreamLine":8, "SourceFile":"\"test-data/src/var-decl-1.c\"", "SourceLine":1, "SourceCol":6 }, 
{}]
````
Because it was arguably ambiguous in the spec how to deal with the quotes, surrounding quotes are
stripped away, so we end up with:
````
[
{ "Text":"int", "Class":"Keyword", "StreamLine":8, "SourceFile":"test-data/src/var-decl-1.c", "SourceLine":1, "SourceCol":1 }, 
{ "Text":"x", "Class":"Identifier", "StreamLine":8, "SourceFile":"test-data/src/var-decl-1.c", "SourceLine":1, "SourceCol":5 }, 
{ "Text":";", "Class":"Operator", "StreamLine":8, "SourceFile":"test-data/src/var-decl-1.c", "SourceLine":1, "SourceCol":6 }, 
{}]
````
So the messages you can see are for the three tokens in the reference.

The JSON given for the include case is:
````
[
{"Class":"Keyword", "Text":"int", "StreamLine":8, "SourceFile":""test-data/src/var-decl-1.c"", "SourceLine": 1, "SourceCol":1},
{"Class":"Identifier", "Text":"x", "StreamLine":8, "SourceFile":""test-data/src/var-decl-1.c"", "SourceLine": 1, "SourceCol":5},
{"Class":"Operator", "Text":";", "StreamLine":8, "SourceFile":""test-data/src/var-decl-1.c"", "SourceLine": 1, "SourceCol":6},
{}
]
````
This is actually not valid JSON - try putting it into a validator, such as [http://jsonlint.com/](http://jsonlint.com/)

So the final line of `include-0.compare.stderr` is:
````
Expecting ',' delimiter: line 2 column 66 (char 67)
````
This indicates that it was unable to parse the JSON. Because stripping the quotes happens
on the loaded JSON, it never gets a change to take off the extra quote marks.

Probably I should have had it load the student JSON first...

**Comment by luisi-at** [comment]
I knew this was invalid JSON after I checked the logs and put it into jsonlint but even after the code was corrected to escape the inner quotations (at a 20% expense, but where this -20% was applied, I'm not certain) does this still count as a test failure? Clearly everything matched as it should but yet the test output was a 0.0% pass rate...? Is this cause for a re-test given that the student JSON should have been loaded first? (Enjoy Lego Batman, I hear it's a good one)

**Comment by m8pple** [comment]
The correction I applied was only the minimal intervention required to fix the bigger
problem of `"SourceFile":, ` mentioned in the notes, so that was the correction to get it
from tiny% to reasonable% (in your case the commit at f4b4ce7d619bdba4febbfb011d72b3e2608d2580).

After that, it passed some large-ish percent of the tokens. The problem with the include cases
is a separate (follow-on) bug. It only becomes apparent after fixing the first bug (to get the
large majority working) that it exposed a bug in a much smaller sub-set (the includes). Fixing
the second bug would be a second intervention, which would attract a second penalty
(some people had the situation where multiple corrections were required in order to get
anything working).

I'm treating this whole thing as exam marking (because this is the examination
of the module knowledge/skills), so the process should be somewhat similar. In an exam you 
can give partial marks for correct reasoning but the wrong working, or some follow-through
marks where an error in one part leads to an error in what would other-wise be correct,
but you can't start erasing or correcting things. Eventually that comes down to
"_Well, they wrote x here,  but they probably meant x^2. But that means they probably
mean exp(x^2) later on, rather than sin(x^2). Well, I'm sure they knew what they were
trying to do._" 

This whole thing about generating valid JSON (and understanding the JSON grammar)
is deeply related to the course core concepts. So while it is partially acting as milestone
to help people get parts of a C compiler built at a reasonably early stage, it is also an
assessment of how well people understand how to read a grammar and generate
compliant output.

The actual ordering of the test versus student JSON is not relevant here, as the reference
JSON passes in all cases, and will not affect the processing of the student JSON, so the
same thing happens regardless of the order.
