### ISSUE TITLE
Extra information in parser xml output

### ISSUE THREAD

**Issue by ps-george** [LangProc/langproc-2016-cw#24]
At the moment I have a lot more information in my print_xml function, namely:

Additional fields inside tags e.g. `<Function id="main" type="int" line="2" col="7">`
More specific tags e.g. `<CompoundStatement>`, `<IfStatement>`
Extra tags e.g. `<ExpressionStatement>`, `<AssignmentStatement>`, `<ReturnStatement>`

I've implemented these using the implicit recursive OOP structure, similar to the pretty_print example in lab 2, and each class will overwrite certain getters to change the contents of the tags based on a general print fucntion defined in the base class. Some classes will override the print() function for specific cases.

My question is, do I have to strip out all of this functionality for the parser deliverable?

If so, I'd appreciate your advice on the best way to do this with respect to Git/rewriting of code.

The way I see it is I could checkout a new branch and then rewrite all my getters, override print() for functions that shouldn't print anything with empty implementation. 

Or introduce a flag that specifies whether to print for the parser deliverable spec or personal debugging usage, and keep everything on master.

Either way it's a lot of "wasted" time and effort, so I'd appreciate it if you have a better idea!

**Comment by m8pple** [comment]
The spec as given says:
```
The output should not contain any other elements except for these five. 
Each element can contain arbitrary amounts of white-space.
```

This gives a closed set of elements, but doesn't say anything
about attributes, so extra attributes like those in your
Function element are fine, they are just extra meta-data
about that node, and they will be ignored by the checker.
I can update the spec to explicitly allow extra attributes
when I'm connected.

-

For the elements, the intent was to restrict things as
much as possible, so that the output could be as simple
as possible and people didn't have to worry about lots
of element types. I don't really mind about other elements,
it was more to make the problem smaller.

I could relax it to say:
````
Additional elements may appear, but will be ignored.
````
but that more covers this scenario:
````
<Program>
    <Variable id="x" />
    <MyExtraElement />
    <Variable id="y" />
</Program>
````
which I don't think helps you.

It sounds like you have something like:
````
<Function>
     <CompoundStatement>
         <Variable id="x" />
     </CompoundStatement>
</Function>
````
which presents a problem, as I don't know what elements are
a scope for each person. If each statement which was a scope
contained a scope, then that could work. So if you had:
````
<Function>
     <CompoundStatement>
         <Scope>
             <Variable id="x" />
         </Scope>
     </CompoundStatement>
</Function>
````
Then I could work with it, as I could use an XPath statement
like `.//(Scope|Variable)` to find any descendant element
I was interested in. However, any element that contained a
scope would need to have an explicit child Scope element of
the correct length.

At this stage I'm a reluctant to do that, as it means
changing the spec in a way that may confuse people (I'd
need to try explaining about descendent nodes and XPath),
and I don't really want to change the test-bench/model
answer at this point.

(As to why I didn't define a tight XML representation of
all the different things, it's because as soon as I define
all the different elements, I've effectively forced an AST
on to people).

-

For this scenario, you probably don't want a seperate branch,
as on a project like this it is more likely to lead to
drift between the two. What you're proposing is something
akin to a custom feature branch, which can be useful in
a big or multi-person project, but is probably too much
overhead here. (Note that I'm not saying don't use branches
in general; a seperate dev and master is still a good
idea if you're happy managing branches).

So at this point, the easiest thing may be to augment your
print function with a flag, or *ahem* use a global, to
control which version of print is active. This is one
of the difficult things about data-structure design,
and it is quite likely that your AST will accumulate cruft
over time. For this project I wouldn't worry too much
about things getting a big ugly, as it has a limited
life-time, so the technical debt is not too large.

As to how you try to avoid the problem (you have lots of
functions over a tree, but some functions are only active
on some parts of the tree), then the general OOP solution
to this is the "visitor pattern" (not on the internet at the
moment, but there should be a decent wikipedia page on it).
However, the visitor pattern is one of those things that
only really makes sense once you've personally encountered
the problem it solves.

ASTs are one place where the visitor pattern is particularly
useful, as there are so many passes that need to walk over
the tree, but some of them want to do it in pre-order (top-down),
some in post-order (bottom-up), and some are only interested in
small parts of the tree. I don't explicitly mention it because
it would add to the cognitive load of the course, and is
conceptually quite difficult to understand until one has
gained a bit of experience designing and working with
real data-structures (like an AST!). Most people only
need a few methods over the AST (e.g. print, dump_scopes,
resolve_variables, compile), which is enough to see
why patterns are useful, but not enough to justify
going back and using it (probably).

David Thomas

**Comment by ps-george** [comment]
Thanks for your advice, next time I come across this I'll explore the visitor pattern but I'm too overloaded with work right now,

For now I just used a global variable (:-1:). It's ugly.

I've left in all the extra attributes so if you could update the spec to explicitly allow additional attributes that would be muchly appreciated.

Thanks!

**Comment by m8pple** [comment]
Yes, you definitely don't want to be looking at extra stuff now.
You'll mostly find that suggested patterns and practises that
people come up with make more sense in the future, as you look
back on what you did now.

It is usually the case that one discovers a good solution to something
when it is too late to apply it, as you have to build so much in order
to get deep enough to understand what the problem is and what
question to ask.
