### ISSUE TITLE
JSON is JSON

### ISSUE THREAD

**Issue by ps-george** [LangProc/langproc-2016-cw#3]
Just checking that it doesn't matter, is this:
```
[
	{
		"Class": "PreprocFile",
		"Text": "# 1 \"test/lexer/in/tmp.c\"",
		"StreamLine": "1",
		"SourceLine": "1",
		"SourceCol": "1",
		"SourceFile": "test/lexer/in/tmp.c"
	},
{}
]
```
The same as this?
```
[{"Class" : "PreprocFile","Text" : "# 1 \"test/lexer/in/tmp.c\"","StreamLine" : "1","SourceLine" : "1","SourceCol" : "1","SourceFile" : "test/lexer/in/tmp.c"},
{}
]
```

**Comment by m8pple** [comment]
Yes, they look identical AFAICT (just white-space changes, maybe ordering).

However, "PreprocFile" is not actually one of the _token_ types (as it is not a token).

**Comment by ps-george** [comment]
Is # an operator?

**Comment by m8pple** [comment]
Things starting with # are pre-processing tokens, rather than tokens. See
page 49, section 6.4:
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf

AFAICT, there is no way of # appearing as a token, unless embedded
in a string or char literal (or maybe through a tri-graph, but I don't think that is
allowed either).

We haven't explicitly pinned it back to the spec, but your lexer is producing
tokens at translation level 7 from the spec, so only tokens should come out
of the other end (though those tokens may have attributes derived from the
pre-processor tokens).
