### ISSUE TITLE
is sizeof a keyword or an operator or both or am I crazy?

### ISSUE THREAD

**Issue by tnugent97** [LangProc/langproc-2016-cw#6]
Title is pretty self explanatory.

_sizeof_ appears as both a keyword and an operator, so which is it?
If I include it as being both, then what will actually happen if _sizeof_ is in the input stream? 
(i.e. what token will it be recognised as and does it matter?)

**Comment by m8pple** [comment]
The token itself is taken to be a keyword for lexing purposes, then for grammatical purposes
it is a kind of operator:
http://en.cppreference.com/w/c/keyword

You can tell it is a keyword rather than an operator by the references to "reserved keywords"
which you'll see mentioned. If not for the fact that the language mandates that `sizeof` is
reserved, it would be treated as an identifier. So a keyword is any kind of lexical token
that would ordinarily be an identifier, but is specially reserved to be a keyword instead.

In comparison, tokens like `(`, `+` and so on would never be considered as an identifier,
and in fact the starting character of the identifiers+keywords is disjoint from the
starting characters of all other token types (I think).

The MS docs touch on this a bit in the context of pre-processing phases:
https://msdn.microsoft.com/en-us/library/befeaky0.aspx
